Feature/no cachear compiled values
bukhr/i18n-recursive-lookup pull request #1
Opened 2023-02-17 20:48 UTC by DanielaCorral

## Issues relacionados

Contexto: [Slack](https://bukhr.slack.com/archives/C03PSQ4RBCZ/p1676396826687299)

## Descripción del problema
Se requiere hacer un fork de la gema `I18n-recursive-lookup` ya que al analizar su flujo nos dimos cuenta que cachea los valores de las traducciones que hace al primer request, lo cual provoca que el tenant obtenga y se quede con los valores de ciertas traducciones que consulta al iniciarse la aplicación. En particular, esto hubiera sido un gran problema para cuando se implemente el [campo de cambio de palabra "empleado"](https://buk.atlassian.net/browse/HCM-2188?atlOrigin=eyJpIjoiZDE1OGY4ZWRmZjdhNDMwZjliZGQ0NTY1OGE3ODM2NWIiLCJwIjoiaiJ9): el cambio no se observaría porque la traducción iría al primer valor cacheado y no se actualizaría con la nueva palabra ingresada por el usuario. 

## Qué se hizo para resolver el problema
Se vio que el problema estaba en el llamado a la función de I18n `store_translations` que se hace dentro de la función `cache_compiled_result` de la gema recursiva. Se cambió ese llamado por `Utils.deep_merge!(I18n.backend.translations[locale], translation_hash)`, que es una línea del método de `store_translations` que actualiza el diccionario de traducciones con el valor obtenido de la recursión, pero sin cachear el valor.

Además, se arreglaron los tests que se rompieron o venían rotos desde la gema y se arreglaron los errores de linter y de convenciones de estilo y se añadió binding.pry para futuro debugging.

## Cómo probar
1. Descargar el repositorio
2. Correr los tests con `rake test test/backend/recursive_lookup_test.rb` y verificar que pasen todos.

2023-02-21 14:56 UTC, fsateler requested changes
Hay un monton de cambios que no tienen mucho que ver... dejemos el minimo necesario, porque eso es lo que deberíamos enviar a la gema original tambien

2023-02-22 13:27 UTC, DMasterIO commented
> Hay un monton de cambios que no tienen mucho que ver... dejemos el minimo necesario, porque eso es lo que deberíamos enviar a la gema original tambien

@fsateler no estoy tan de acuerdo en esto, muchos de los cambios son para pasar los build de la misma gema que no estaban pasando. Veo 2 temas con "hacer los cambios minimos"
- Somos nosotros los encargados hasta que la gema apruebe el cambio de mantener este fork. *Lo minimo* es que este pasando los test, nos puede jugar en contra si dejamos algo "al azar" especialmente ahora que se viene todo el proceso de traducciones e i18n de la app. 
- 100% de acuerdo con que debemos enviar este PR a la gema, pero es una gema sin mantención y desde hace 7 años y donde su propia build y test no pasan. si la vamos a utilizar en buk y vamos a mandar un aporte al OpenSource debe ser con todo (sino, pa q').

Y por último pero no menos importante se han invertido varias(muchas) horas en dejar este fork funcionando lo mejor posible.

2023-02-22 13:28 UTC, DMasterIO commented
@DanielaCorral ordenemos los commits, el último me suena casi a un "fix del cache" y eso en teoría es parte del feat.

2023-02-22 13:31 UTC, DMasterIO requested changes

2023-02-22 13:31 UTC, DMasterIO commented on test/backend/recursive_lookup_test.rb
> -  test "still returns an existing translation as usual" do
en el standar de buk los test van en español, pero esta gema es OS y tenemos que enviar este PR a la gema oficial, por lo que debemos mantener el standar en ingles

2023-02-22 13:31 UTC, DMasterIO commented on test/backend/recursive_lookup_test.rb
> -  test "does a lookup on an embedded key" do
lo mismo por acá, el titulo deberá ser en ingles por que la idea es enviar estos cambios a la gema original

2023-02-22 13:31 UTC, DMasterIO commented on test/backend/recursive_lookup_test.rb
> -  test "correctly translates a hash reference when called directly" do
porque estamos comentando estos test?
- Si el test no nos hace sentido, se elimina
- Si el test hace sentido pero no esta corriendo se corrije

No dejemos lineas de código basura ;)

2023-02-22 14:16 UTC, jvlara requested changes

2023-02-22 14:16 UTC, jvlara commented on lib/i18n/backend/recursive_lookup.rb
> -      INTERPOLATION_SYNTAX_PATTERN = /(\$)?(\$\{([^\}]+)\})/
¿Cual fue la razón por la que quitamos que no tenga \?

2023-02-22 14:16 UTC, jvlara commented on lib/i18n/backend/recursive_lookup.rb
> +      # rubocop:disable Metrics/MethodLength
La gema no tenia rubocop así que quitemos este comentario

2023-02-22 14:16 UTC, jvlara commented on lib/i18n/backend/recursive_lookup.rb
> +          # compiled a new reference with our key, otherwise still stay nil
Si solo cambiamos los comentarios de linea añadamoslo en otro commit diferente

2023-02-22 14:16 UTC, jvlara commented on lib/i18n/backend/recursive_lookup.rb
Si bien no ocuparemos cache en buk para la gema en mil años más o quizas dos mil nos puedan aceptar el pr, así que dejaria que nuestro comportamiento de no tener cache sea opcional: 
```ruby
attr_writer :enabled_interpolation_cache

def enabled_interpolation_cache
  @enabled_interpolation_cache ||= true
end
alias enabled_interpolation_cache? enabled_interpolation_cache
```

2023-02-22 14:16 UTC, jvlara commented on lib/i18n/backend/recursive_lookup.rb
> +        # cache_compiled_result(locale, key, compiled_result, scope, options) if had_to_compile_result
Siguiendo el hilo de dejar opcional la lógica de no cachear, dejemoslo así 
```ruby
if enabled_interpolation_cache? && had_to_compile_result
  cache_compiled_result(locale, key, compiled_result, scope, options)
end
```

2023-02-22 14:16 UTC, jvlara commented on lib/i18n/backend/recursive_lookup.rb
>        end
Siguiendo el hilo de no cachear dejemoslo as
```ruby
def deep_compile(locale, subject, options)
  subject = subject.clone unless enabled_interpolation_cache?
  if subject.is_a?(Hash)
    subject.each do |key, object|
      subject[key], = deep_compile(locale, object, options)
    end
  else
    compile(locale, subject, options)
  end
end
```

2023-02-22 14:16 UTC, jvlara commented on lib/i18n/backend/recursive_lookup.rb
> +      # def cache_compiled_result(locale, dot_form_key, compiled_result, scope, options)
Dejemos este metodo tal cual estaba en la gema 
```ruby
      def cache_compiled_result(locale, dot_form_key, compiled_result, scope, options)
        keys = I18n.normalize_keys(locale, dot_form_key, scope, options[:separator])

        translation_hash = {}
        # ignore prepended locale key
        keys[1..-1].inject(translation_hash) do |hash, key|
          key == keys[-1] ? hash[key] = compiled_result : hash[key] = {}
        end

        store_translations(locale, translation_hash, options)
      end
```

2023-02-22 14:16 UTC, jvlara commented on test/backend/recursive_lookup_test.rb
>  class I18nBackendRecursiveLookupTest < Test::Unit::TestCase
Dejemos todos los test tal cual estaban en la gema y hagamos otro contexto donde hagamos algo así 
```ruby
context 'with cache for interpolated translations disabled' do 
  setup do 
     I18n.backend.enabled_interpolation_cache = false
  end
  # nuestros test nuevos en ingles
end 
```

2023-02-22 14:20 UTC, jvlara commented on lib/i18n/backend/recursive_lookup.rb
> +          # compiled a new reference with our key, otherwise still stay nil
tambien reordenar todos los commits y hacerlos en ingles

2023-02-22 14:28 UTC, jvlara requested changes

2023-02-22 14:28 UTC, jvlara commented on gemfiles/Gemfile.bare
> +gem 'pry-nav'
Aquí estamos añadiendo las gemas de debuggueo para todos los entornos, lo cual es malo ya que en productivo o cuando alguien instale la gema estas se instalaran tambien

Para evitar esto podemos ir a `i18n-recursive-lookup.gemspec` y añadir las siguientes lineas 
```ruby
  s.add_development_dependency 'pry'
  s.add_development_dependency 'pry-remote'
  s.add_development_dependency 'pry-nav'
```

2023-02-22 14:31 UTC, DanielaCorral commented on test/backend/recursive_lookup_test.rb
>  class I18nBackendRecursiveLookupTest < Test::Unit::TestCase
intenté hacer `context` antes en este repo pero no funciona, acaso necesitará una gema extra?

2023-02-22 14:34 UTC, jvlara commented on test/backend/recursive_lookup_test.rb
>  class I18nBackendRecursiveLookupTest < Test::Unit::TestCase
ahhhh fak, toda la razon, no tienen minitest

2023-02-22 14:36 UTC, DanielaCorral commented on lib/i18n/backend/recursive_lookup.rb
> -      INTERPOLATION_SYNTAX_PATTERN = /(\$)?(\$\{([^\}]+)\})/
Acabo de dejarlo como estaba pero antes lo había cambiado por el linter de estilo :eyes:

2023-02-22 14:39 UTC, jvlara commented on test/backend/recursive_lookup_test.rb
>  class I18nBackendRecursiveLookupTest < Test::Unit::TestCase
mmm según mi investigación de 3 minutos cache que para hacer un contexto diferente en ese framework de test hay que hacer una nueva clase 

```ruby
class I18nBackendRecursiveLookupWithoutCacheTest < Test::Unit::TestCase
  class Backend < I18n::Backend::Simple
    include I18n::Backend::RecursiveLookup
  end

  # rubocop:disable Metrics/MethodLength
  def setup
    I18n.backend = Backend.new
    I18n.backend.store_translations(
      :en,
      foo: 'foo',
      bar: {
        baz: 'bar ${foo}',
        boo: {
          baz: 'hoo ${bar.baz}'
        }
      },
      alternate_lookup: '${baz}',
      hash_lookup: '${hash}',
      hash_lookup_no_deeper: '${hash_no_deeper}',
      hash: {
        one: 'hash',
        other: 'hashes',
        deeper: {
          first: 'First hash',
          second: 'Second hash'
        }
      },
      hash_no_deeper: {
        one: 'hash',
        other: 'hashes'
      },
      number_hash: {
        format: {
          delimiter: ',',
          precision: 3,
          significant: false
        }
      }
    )
    I18n.enabled_interpolation_cache = true
  end
  # tests
```

2023-02-22 14:40 UTC, jvlara commented on test/backend/recursive_lookup_test.rb
>  class I18nBackendRecursiveLookupTest < Test::Unit::TestCase
![image](https://user-images.githubusercontent.com/26396425/220655437-3d7d053f-bbbe-4b2d-b2c4-a6c046536eab.png)
https://test-unit.github.io/test-unit/en/Test/Unit.html#:~:text=Test%3A%3AUnit%3A%3ATestCase,test%20method%20that%20is%20run.

2023-02-22 14:44 UTC, DanielaCorral commented on test/backend/recursive_lookup_test.rb
>  class I18nBackendRecursiveLookupTest < Test::Unit::TestCase
Y cómo se lo puedo agregar? O mejor no lo agrego?

2023-02-22 14:50 UTC, jvlara commented on test/backend/recursive_lookup_test.rb
>  class I18nBackendRecursiveLookupTest < Test::Unit::TestCase
agrega una nueva clase abajo de la original con lo que puse en el comentario 👌🏼

2023-02-22 15:00 UTC, DanielaCorral commented on test/backend/recursive_lookup_test.rb
>  class I18nBackendRecursiveLookupTest < Test::Unit::TestCase
No lo agregaré :eyes: Justificación: [Slack](https://bukhr.slack.com/archives/C03PSQ4RBCZ/p1677077776641289)

2023-02-22 15:28 UTC, orlandopcr commented on gemfiles/Gemfile.bare
> +gem 'pry-nav'
Yo le metí el debugueo para que sea más fácil avanzar para nosotros. Si vamos a hacer el pr a la gema le sacaría el pry nomás

2023-02-22 16:29 UTC, DanielaCorral commented on gemfiles/Gemfile.bare
> +gem 'pry-nav'
Eliminado el pry :+1:

2023-02-22 23:46 UTC, jvlara approved these changes

2023-02-22 23:50 UTC, DMasterIO approved these changes

2023-02-23 08:25 UTC, fsateler requested changes

2023-02-23 08:25 UTC, fsateler commented on lib/i18n/backend/recursive_lookup.rb
> +        @enabled_interpolation_cache = @enabled_interpolation_cache.nil? ? true : @enabled_interpolation_cache
Creo que es mas sencillo definir el default a true en el constructor

2023-02-23 08:25 UTC, fsateler commented on test/backend/recursive_lookup_test.rb
> +class I18nBackendRecursiveLookupWithoutCacheTest < Test::Unit::TestCase
falta el test que realmente se reevaluan las traducciones? Es decir, que si cambia `foo`, la traduccion `${foo}` es reevaluada

2023-02-23 08:35 UTC, fsateler commented on lib/i18n/backend/recursive_lookup.rb
> +      def enabled_interpolation_cache
`enable` (sin d).

2023-02-23 14:52 UTC, fsateler approved these changes

2023-02-23 15:08 UTC, merged